const DEFAULT_FLEXIOT_EMAIL = "=";
const DEFAULT_FLEXIOT_PASSWORD = "";
const DEFAULT_FLEXIOT_USER_ID = 73777;
const DEFAULT_FLEXIOT_X_SECRET = "";
const DEFAULT_FLEXIOT_MQTT_USERNAME = "";
const DEFAULT_FLEXIOT_MQTT_PASSWORD = "";
const DEFAULT_FLEXIOT_MQTT_EVENT_TOPIC = "";
const DEFAULT_FLEXIOT_MQTT_URL = "mqtt://devdeviceconnect3";

module.exports = {
  DEFAULT_FLEXIOT_EMAIL,
  DEFAULT_FLEXIOT_PASSWORD,
  DEFAULT_FLEXIOT_X_SECRET,
  DEFAULT_FLEXIOT_USER_ID,
  DEFAULT_FLEXIOT_MQTT_USERNAME,
  DEFAULT_FLEXIOT_MQTT_PASSWORD,
  DEFAULT_FLEXIOT_MQTT_EVENT_TOPIC,
  DEFAULT_FLEXIOT_MQTT_URL,
}
